In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
billboard = pd.read_csv('billboard_hot_100.csv')

In [3]:
#billboard.head()

In [4]:
spotify = pd.read_csv('spotify_top_50.csv')

In [5]:
#spotify.head()

In [6]:
spotify = spotify.drop(['Genre', 'Beats.Per.Minute', 'Energy', 'Danceability', 'Loudness..dB..', 'Liveness','Valence.', 'Length.','Acousticness..','Speechiness.','Popularity'],axis=1)

In [7]:
#spotify.head()

In [8]:
spotify = spotify.rename(columns = {'Unnamed: 0':'No.','Track.Name':'Title', 'Artist.Name':'Artist(s)'})

In [9]:
spotify.head()

   No.                            Title      Artist(s)
0    1                         Señorita   Shawn Mendes
1    2                            China       Anuel AA
2    3    boyfriend (with Social House)  Ariana Grande
3    4  Beautiful People (feat. Khalid)     Ed Sheeran
4    5      Goodbyes (Feat. Young Thug)    Post Malone

In [10]:
billboard.head()

   No.            Title                               Artist
0    1  "Old Town Road"  Lil Nas X featuring Billy Ray Cyrus
1    2      "Sunflower"             Post Malone and Swae Lee
2    3     "Without Me"                               Halsey
3    4        "Bad Guy"                        Billie Eilish
4    5            "Wow"                          Post Malone

In [11]:
spotify['Artist(s)'].unique()

array(['Shawn Mendes', 'Anuel AA', 'Ariana Grande', 'Ed Sheeran',
       'Post Malone', 'Lil Tecca', 'Sam Smith', 'Lil Nas X',
       'Billie Eilish', 'Bad Bunny', 'DJ Snake', 'Lewis Capaldi', 'Sech',
       'Drake', 'Chris Brown', 'J Balvin', 'Y2K', 'Lizzo', 'MEDUZA',
       'Jhay Cortez', 'Lunay', 'Tones and I', 'Ali Gatie', 'Daddy Yankee',
       'The Chainsmokers', 'Maluma', 'Young Thug', 'Katy Perry',
       'Martin Garrix', 'Jonas Brothers', 'Lauv', 'Kygo', 'Taylor Swift',
       'Lady Gaga', 'Khalid', 'ROSALÍA', 'Marshmello', 'Nicky Jam'],
      dtype=object)

In [12]:
billboard['Artist'].unique()

array(['Lil Nas X\xa0featuring\xa0Billy Ray Cyrus',
       'Post Malone\xa0and\xa0Swae Lee', 'Halsey', 'Billie Eilish',
       'Post Malone', 'Marshmello\xa0and\xa0Bastille', 'Ariana Grande',
       'Khalid', 'Travis Scott', 'Jonas Brothers', 'Panic! at the Disco',
       'Lizzo', 'Sam Smith\xa0and\xa0Normani',
       'Shawn Mendes\xa0and\xa0Camila Cabello',
       'Ed Sheeran\xa0and\xa0Justin Bieber',
       'Benny Blanco,\xa0Halsey\xa0and\xa0Khalid',
       'Meek Mill\xa0featuring\xa0Drake',
       'Lady Gaga\xa0and\xa0Bradley Cooper',
       'Chris Brown\xa0featuring\xa0Drake',
       'Maroon 5\xa0featuring\xa0Cardi B', 'Ava Max', 'DaBaby', 'J. Cole',
       'Lil Baby\xa0and\xa0Gunna', 'Lewis Capaldi', 'Lil Tecca',
       'Shawn Mendes', 'Post Malone\xa0featuring\xa0Young Thug',
       'Kodak Black\xa0featuring\xa0Travis Scott\xa0and\xa0Offset',
       '5 Seconds of Summer', 'Drake\xa0featuring\xa0Rick Ross',
       'Dan + Shay', 'Cardi B\xa0and\xa0Bruno Mars', 'Cardi B',
       'Taylor Swift', 'Lil Nas X', 'A Boogie wit da Hoodie', '21 Savage',
       'Taylor Swift\xa0featuring\xa0Brendon Urie',
       'Bad Bunny\xa0featuring\xa0Drake',
       'Polo G\xa0featuring\xa0Lil Tjay', 'Luke Combs', 'Blueface',
       'Juice Wrld', 'Sheck Wes', 'Ed Sheeran\xa0featuring\xa0Khalid',
       'Gucci Mane,\xa0Bruno Mars\xa0and\xa0Kodak Black', 'Morgan Wallen',
       'Blake Shelton', 'Dean Lewis', 'Mustard\xa0and\xa0Migos',
       'Blanco Brown',
       'DJ Snake\xa0featuring\xa0Selena Gomez,\xa0Ozuna\xa0and\xa0Cardi B',
       'Ellie Goulding\xa0and\xa0Diplo\xa0featuring\xa0Swae Lee',
       'Calboy', 'Lauren Daigle',
       'Young Thug,\xa0J. Cole\xa0and\xa0Travis Scott',
       'Daddy Yankee\xa0and\xa0Katy Perry\xa0featuring\xa0Snow',
       'YNW Melly', 'City Girls',
       'Cardi B,\xa0Bad Bunny\xa0and\xa0J Balvin', 'Shaed',
       'Flipp Dinero', 'Lil Baby', 'Pinkfong', 'Saweetie', 'YK Osiris',
       'Luke Bryan', 'Ella Mai', 'Lee Brice',
       'A Boogie wit da Hoodie\xa0featuring\xa06ix9ine', 'Sam Smith',
       'Lil Baby\xa0and\xa0DaBaby', 'Thomas Rhett', 'Kane Brown',
       'Offset\xa0featuring\xa0Cardi B', 'Khalid\xa0and\xa0Normani',
       'Marshmello\xa0and\xa0Kane Brown',
       'Megan Thee Stallion\xa0featuring\xa0DaBaby', 'NLE Choppa',
       'Megan Thee Stallion\xa0featuring\xa0Nicki Minaj\xa0and\xa0Ty Dolla Sign',
       'Florida Georgia Line', 'Bazzi\xa0featuring\xa0Camila Cabello',
       'Chase Rice', 'Ariana Grande\xa0and\xa0Social House', 'Pink'],
      dtype=object)

In [13]:
split_data = billboard['Artist'].str.split("\xa0")
data = split_data.to_list() 
name = ['Artist','1','2','3','4','5']
new_df = pd.DataFrame(data, columns=name)

In [14]:
new_df

           Artist          1                2     3     4     5
0       Lil Nas X  featuring  Billy Ray Cyrus  None  None  None
1     Post Malone        and         Swae Lee  None  None  None
2          Halsey       None             None  None  None  None
3   Billie Eilish       None             None  None  None  None
4     Post Malone       None             None  None  None  None
..            ...        ...              ...   ...   ...   ...
95     Chase Rice       None             None  None  None  None
96     Dan + Shay       None             None  None  None  None
97  Ariana Grande        and     Social House  None  None  None
98           Pink       None             None  None  None  None
99     Juice Wrld       None             None  None  None  None

[100 rows x 6 columns]

In [15]:
new_df.head()
new_df = new_df.drop(['1','2','3','4','5'], axis=1)
new_df.head()

          Artist
0      Lil Nas X
1    Post Malone
2         Halsey
3  Billie Eilish
4    Post Malone

In [16]:
# pd.Series(new_df)
billboard_artist= new_df.iloc[:,0]
billboard["Artist(s)"]=billboard_artist
billboard = billboard.drop(["Artist"], axis=1)

In [17]:
billboard

    No.            Title      Artist(s)
0     1  "Old Town Road"      Lil Nas X
1     2      "Sunflower"    Post Malone
2     3     "Without Me"         Halsey
3     4        "Bad Guy"  Billie Eilish
4     5            "Wow"    Post Malone
..  ...              ...            ...
95   96    "Eyes on You"     Chase Rice
96   97  "All to Myself"     Dan + Shay
97   98      "Boyfriend"  Ariana Grande
98   99   "Walk Me Home"           Pink
99  100        "Robbery"     Juice Wrld

[100 rows x 3 columns]

In [18]:
billboard["Title"]=billboard.iloc[:, 1].str.replace('"', '')

In [19]:
billboard

    No.          Title      Artist(s)
0     1  Old Town Road      Lil Nas X
1     2      Sunflower    Post Malone
2     3     Without Me         Halsey
3     4        Bad Guy  Billie Eilish
4     5            Wow    Post Malone
..  ...            ...            ...
95   96    Eyes on You     Chase Rice
96   97  All to Myself     Dan + Shay
97   98      Boyfriend  Ariana Grande
98   99   Walk Me Home           Pink
99  100        Robbery     Juice Wrld

[100 rows x 3 columns]

In [20]:
spotify['Title'].unique()

array(['Señorita', 'China', 'boyfriend (with Social House)',
       'Beautiful People (feat. Khalid)', 'Goodbyes (Feat. Young Thug)',
       "I Don't Care (with Justin Bieber)", 'Ransom', 'How Do You Sleep?',
       'Old Town Road - Remix', 'bad guy', 'Callaita',
       'Loco Contigo (feat. J. Balvin & Tyga)', 'Someone You Loved',
       'Otro Trago - Remix', 'Money In The Grave (Drake ft. Rick Ross)',
       'No Guidance (feat. Drake)', 'LA CANCIÓN',
       'Sunflower - Spider-Man: Into the Spider-Verse', 'Lalala',
       'Truth Hurts', 'Piece Of Your Heart', 'Panini',
       'No Me Conoce - Remix', 'Soltera - Remix',
       'bad guy (with Justin Bieber)', "If I Can't Have You",
       'Dance Monkey', "It's You", 'Con Calma', 'QUE PRETENDES',
       'Takeaway', '7 rings', '0.958333333',
       'The London (feat. J. Cole & Travis Scott)', 'Never Really Over',
       'Summer Days (feat. Macklemore & Patrick Stump of Fall Out Boy)',
       'Otro Trago', 'Antisocial (with Travis Scott)', 'Sucker',
       "fuck, i'm lonely (with Anne-Marie) - from “13 Reasons Why: Season 3”",
       'Higher Love', 'You Need To Calm Down', 'Shallow', 'Talk',
       'Con Altura', 'One Thing Right', 'Te Robaré', 'Happier',
       'Call You Mine', 'Cross Me (feat. Chance the Rapper & PnB Rock)'],
      dtype=object)

In [21]:
split_data = spotify['Title'].str.split("(")
data = split_data.to_list() 
data
name = ['Title','1']
new_df = pd.DataFrame(data, columns=name)
new_df = new_df.drop(['1'], axis=1)
new_df

                                            Title
0                                        Señorita
1                                           China
2                                      boyfriend
3                               Beautiful People
4                                       Goodbyes
5                                   I Don't Care
6                                          Ransom
7                               How Do You Sleep?
8                           Old Town Road - Remix
9                                         bad guy
10                                       Callaita
11                                  Loco Contigo
12                              Someone You Loved
13                             Otro Trago - Remix
14                            Money In The Grave
15                                   No Guidance
16                                     LA CANCIÓN
17  Sunflower - Spider-Man: Into the Spider-Verse
18                                         Lalala
19                                    Truth Hurts
20                            Piece Of Your Heart
21                                         Panini
22                           No Me Conoce - Remix
23                                Soltera - Remix
24                                       bad guy
25                            If I Can't Have You
26                                   Dance Monkey
27                                       It's You
28                                      Con Calma
29                                  QUE PRETENDES
30                                       Takeaway
31                                        7 rings
32                                    0.958333333
33                                    The London
34                              Never Really Over
35                                   Summer Days
36                                     Otro Trago
37                                    Antisocial
38                                         Sucker
39                              fuck, i'm lonely
40                                    Higher Love
41                          You Need To Calm Down
42                                        Shallow
43                                           Talk
44                                     Con Altura
45                                One Thing Right
46                                      Te Robaré
47                                        Happier
48                                  Call You Mine
49                                      Cross Me

In [32]:
spotify_title= new_df.iloc[:,0]
spotify["Title"]=spotify_title
# spotify = spotify.drop(["Title"], axis=1)
spotify.reset_index()

    index  No                                          Title            Artist
0       0   1                                       Señorita      Shawn Mendes
1       1   2                                          China          Anuel AA
2       2   3                                     boyfriend      Ariana Grande
3       3   4                              Beautiful People         Ed Sheeran
4       4   5                                      Goodbyes        Post Malone
5       5   6                                  I Don't Care         Ed Sheeran
6       6   7                                         Ransom         Lil Tecca
7       7   8                              How Do You Sleep?         Sam Smith
8       8   9                          Old Town Road - Remix         Lil Nas X
9       9  10                                        bad guy     Billie Eilish
10     10  11                                       Callaita         Bad Bunny
11     11  12                                  Loco Contigo           DJ Snake
12     12  13                              Someone You Loved     Lewis Capaldi
13     13  14                             Otro Trago - Remix              Sech
14     14  15                            Money In The Grave              Drake
15     15  16                                   No Guidance        Chris Brown
16     16  17                                     LA CANCIÓN          J Balvin
17     17  18  Sunflower - Spider-Man: Into the Spider-Verse       Post Malone
18     18  19                                         Lalala               Y2K
19     19  20                                    Truth Hurts             Lizzo
20     20  21                            Piece Of Your Heart            MEDUZA
21     21  22                                         Panini         Lil Nas X
22     22  23                           No Me Conoce - Remix       Jhay Cortez
23     23  24                                Soltera - Remix             Lunay
24     24  25                                       bad guy      Billie Eilish
25     25  26                            If I Can't Have You      Shawn Mendes
26     26  27                                   Dance Monkey       Tones and I
27     27  28                                       It's You         Ali Gatie
28     28  29                                      Con Calma      Daddy Yankee
29     29  30                                  QUE PRETENDES          J Balvin
30     30  31                                       Takeaway  The Chainsmokers
31     31  32                                        7 rings     Ariana Grande
32     32  33                                    0.958333333            Maluma
33     33  34                                    The London         Young Thug
34     34  35                              Never Really Over        Katy Perry
35     35  36                                   Summer Days      Martin Garrix
36     36  37                                     Otro Trago              Sech
37     37  38                                    Antisocial         Ed Sheeran
38     38  39                                         Sucker    Jonas Brothers
39     39  40                              fuck, i'm lonely               Lauv
40     40  41                                    Higher Love              Kygo
41     41  42                          You Need To Calm Down      Taylor Swift
42     42  43                                        Shallow         Lady Gaga
43     43  44                                           Talk            Khalid
44     44  45                                     Con Altura           ROSALÍA
45     45  46                                One Thing Right        Marshmello
46     46  47                                      Te Robaré         Nicky Jam
47     47  48                                        Happier        Marshmello
48     48  49                                  Call You Mine  The Chainsmokers
49     49  50                                      Cross Me         Ed Sheeran

In [47]:
spotify.rename(columns={"Artist(s)":"Artist"}, inplace=True)
spotify.rename(columns={"No":"Chart_Number"}, inplace=True)
spotify.reset_index()

,index,Chart_Number,Title,Artist
0,0,1,Señorita,Shawn Mendes
1,1,2,China,Anuel AA
2,2,3,boyfriend,Ariana Grande
3,3,4,Beautiful People,Ed Sheeran
4,4,5,Goodbyes,Post Malone
5,5,6,I Don't Care,Ed Sheeran
6,6,7,Ransom,Lil Tecca
7,7,8,How Do You Sleep?,Sam Smith
8,8,9,Old Town Road - Remix,Lil Nas X
9,9,10,bad guy,Billie Eilish
10,10,11,Callaita,Bad Bunny
11,11,12,Loco Contigo,DJ Snake
12,12,13,Someone You Loved,Lewis Capaldi
13,13,14,Otro Trago - Remix,Sech
14,14,15,Money In The Grave,Drake
15,15,16,No Guidance,Chris Brown
16,16,17,LA CANCIÓN,J Balvin
17,17,18,Sunflower - Spider-Man: Into the Spider-Verse,Post Malone
18,18,19,Lalala,Y2K
19,19,20,Truth Hurts,Lizzo
20,20,21,Piece Of Your Heart,MEDUZA
21,21,22,Panini,Lil Nas X
22,22,23,No Me Conoce - Remix,Jhay Cortez
23,23,24,Soltera - Remix,Lunay
24,24,25,bad guy,Billie Eilish
25,25,26,If I Can't Have You,Shawn Mendes
26,26,27,Dance Monkey,Tones and I
27,27,28,It's You,Ali Gatie
28,28,29,Con Calma,Daddy Yankee
29,29,30,QUE PRETENDES,J Balvin
30,30,31,Takeaway,The Chainsmokers
31,31,32,7 rings,Ariana Grande
32,32,33,0.958333333,Maluma
33,33,34,The London,Young Thug
34,34,35,Never Really Over,Katy Perry
35,35,36,Summer Days,Martin Garrix
36,36,37,Otro Trago,Sech
37,37,38,Antisocial,Ed Sheeran
38,38,39,Sucker,Jonas Brothers
39,39,40,"fuck, i'm lonely",Lauv
40,40,41,Higher Love,Kygo
41,41,42,You Need To Calm Down,Taylor Swift
42,42,43,Shallow,Lady Gaga
43,43,44,Talk,Khalid
44,44,45,Con Altura,ROSALÍA
45,45,46,One Thing Right,Marshmello
46,46,47,Te Robaré,Nicky Jam
47,47,48,Happier,Marshmello
48,48,49,Call You Mine,The Chainsmokers
49,49,50,Cross Me,Ed Sheeran

In [45]:
billboard.rename(columns={"Artist(s)":"Artist", "No":"Chart_Number"}, inplace=True)
billboard

    Chart_Number          Title         Artist
0              1  Old Town Road      Lil Nas X
1              2      Sunflower    Post Malone
2              3     Without Me         Halsey
3              4        Bad Guy  Billie Eilish
4              5            Wow    Post Malone
..           ...            ...            ...
95            96    Eyes on You     Chase Rice
96            97  All to Myself     Dan + Shay
97            98      Boyfriend  Ariana Grande
98            99   Walk Me Home           Pink
99           100        Robbery     Juice Wrld

[100 rows x 3 columns]

In [23]:
connection_string = "postgres:postgres@localhost:5432/ETL"
engine = create_engine(f'postgresql://{connection_string}')

In [35]:
engine.table_names()

['billboard', 'spotify']

In [49]:
spotify.to_sql(name='spotify', con=engine, if_exists='append', index=True)

In [50]:
billboard.to_sql(name='billboard', con=engine, if_exists='append', index=True)